/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllData: typeof import('./src/components/DataStruct/AllData.vue')['default']
    Award: typeof import('./src/components/Lottie/Award.vue')['default']
    Chart: typeof import('./src/components/Charts/Chart.vue')['default']
    Content: typeof import('./src/components/Content/Content.vue')['default']
    Detail: typeof import('./src/components/Detail/Detail.vue')['default']
    DetailItem: typeof import('./src/components/Detail/DetailItem.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    NavBar: typeof import('./src/components/Nav/NavBar.vue')['default']
    Person: typeof import('./src/components/DataStruct/Person.vue')['default']
    RollButton: typeof import('./src/components/Content/RollButton.vue')['default']
    Student: typeof import('./src/components/Student/Student.vue')['default']
    TopOne: typeof import('./src/components/PersonalPart/TopOne.vue')['default']
    TopThree: typeof import('./src/components/PersonalPart/TopThree.vue')['default']
    TopTwo: typeof import('./src/components/PersonalPart/TopTwo.vue')['default']
  }
}
